project:
  type: website

website:
  title: "Using Python To Conduct Chi2 Analyses"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Data Maker
        menu:
          - href: data-maker.qmd
            text: Data Maker
          - href: data-preview.qmd
            text: Data Preview
      - text: Chi-Square Tutorials
        menu:
          - href: chi2-example-tutorial-airport.qmd
            text: Airport Routes
          - href: chi2-example-tutorial-airport-python.qmd
            text: Airport Routes in Python
          - href: chi2-example-tutorial-airport-pragmatic.qmd
            text: Airport Routes, Pragmatic
          - href: chi2-example-tutorial-math.qmd
            text: Math Programs
      - about.qmd

format:
  html:
    lang: en
    theme: cosmo
    css: styles.css
    toc: true



