project:
  type: website

website:
  title: "Using Python To Conduct Chi2 Analyses"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Data Maker
        menu:
          - href: data-maker.qmd
            text: Data Maker
          - href: data-preview.qmd
            text: Data Preview
      - href: chi2-example-tutorial.qmd
        text: Chi-Square Tutorial
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



