<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.39">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Adam Ross Nelson">
<meta name="dcterms.date" content="2026-09-29">
<meta name="description" content="A step-by-step, self-paced walkthrough of the chi-square test of independence, using a fictional survey of Southwestern Madison travelers and their routes to the airport. Includes a reference table of chi-square critical values.">

<title>Chi-Square Test of Independence: A Worked Example (Airport Routes) – Using Python To Conduct Chi2 Analyses</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-e26003cea8cd680ca0c55a263523d882.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-6bd9cfa162949bde0a231f530c97869d.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Using Python To Conduct Chi2 Analyses</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-data-maker" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Data Maker</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-data-maker">    
        <li>
    <a class="dropdown-item" href="./data-maker.html">
 <span class="dropdown-text">Data Maker</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./data-preview.html">
 <span class="dropdown-text">Data Preview</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-chi-square-tutorials" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Chi-Square Tutorials</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-chi-square-tutorials">    
        <li>
    <a class="dropdown-item" href="./chi2-example-tutorial-airport.html">
 <span class="dropdown-text">Airport Routes</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./chi2-example-tutorial-airport-python.html">
 <span class="dropdown-text">Airport Routes in Python</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./chi2-example-tutorial-airport-pragmatic.html">
 <span class="dropdown-text">Airport Routes, Pragmatic</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./chi2-example-tutorial-math.html">
 <span class="dropdown-text">Math Programs</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="./about.html"> 
<span class="menu-text">About</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#what-you-will-learn" id="toc-what-you-will-learn" class="nav-link active" data-scroll-target="#what-you-will-learn">What you will learn</a></li>
  <li><a href="#the-big-idea" id="toc-the-big-idea" class="nav-link" data-scroll-target="#the-big-idea">The big idea</a></li>
  <li><a href="#the-scenario" id="toc-the-scenario" class="nav-link" data-scroll-target="#the-scenario">The scenario</a></li>
  <li><a href="#the-hypotheses" id="toc-the-hypotheses" class="nav-link" data-scroll-target="#the-hypotheses">The hypotheses</a></li>
  <li><a href="#the-data" id="toc-the-data" class="nav-link" data-scroll-target="#the-data">The data</a></li>
  <li><a href="#the-formula" id="toc-the-formula" class="nav-link" data-scroll-target="#the-formula">The formula</a></li>
  <li><a href="#step-1-calculate-the-expected-values" id="toc-step-1-calculate-the-expected-values" class="nav-link" data-scroll-target="#step-1-calculate-the-expected-values">Step 1: Calculate the expected values</a>
  <ul class="collapse">
  <li><a href="#what-is-an-expected-value" id="toc-what-is-an-expected-value" class="nav-link" data-scroll-target="#what-is-an-expected-value">What is an expected value?</a></li>
  <li><a href="#the-recipe" id="toc-the-recipe" class="nav-link" data-scroll-target="#the-recipe">The recipe</a></li>
  <li><a href="#worked-example-1-madison-native-north" id="toc-worked-example-1-madison-native-north" class="nav-link" data-scroll-target="#worked-example-1-madison-native-north">Worked example 1: Madison native, North</a></li>
  <li><a href="#worked-example-2-greater-madison-native-isthmus" id="toc-worked-example-2-greater-madison-native-isthmus" class="nav-link" data-scroll-target="#worked-example-2-greater-madison-native-isthmus">Worked example 2: Greater Madison native, Isthmus</a></li>
  <li><a href="#the-full-matrix-of-expected-values" id="toc-the-full-matrix-of-expected-values" class="nav-link" data-scroll-target="#the-full-matrix-of-expected-values">The full matrix of expected values</a></li>
  </ul></li>
  <li><a href="#step-2-calculate-the-normalized-errors" id="toc-step-2-calculate-the-normalized-errors" class="nav-link" data-scroll-target="#step-2-calculate-the-normalized-errors">Step 2: Calculate the normalized errors</a>
  <ul class="collapse">
  <li><a href="#worked-example-madison-native-north" id="toc-worked-example-madison-native-north" class="nav-link" data-scroll-target="#worked-example-madison-native-north">Worked example: Madison native, North</a></li>
  <li><a href="#a-second-example-greater-madison-native-isthmus" id="toc-a-second-example-greater-madison-native-isthmus" class="nav-link" data-scroll-target="#a-second-example-greater-madison-native-isthmus">A second example: Greater Madison native, Isthmus</a></li>
  <li><a href="#the-full-matrix-of-normalized-errors" id="toc-the-full-matrix-of-normalized-errors" class="nav-link" data-scroll-target="#the-full-matrix-of-normalized-errors">The full matrix of normalized errors</a></li>
  </ul></li>
  <li><a href="#step-3-add-them-up-to-get-the-chi-square-statistic" id="toc-step-3-add-them-up-to-get-the-chi-square-statistic" class="nav-link" data-scroll-target="#step-3-add-them-up-to-get-the-chi-square-statistic">Step 3: Add them up to get the chi-square statistic</a></li>
  <li><a href="#step-4-find-the-degrees-of-freedom" id="toc-step-4-find-the-degrees-of-freedom" class="nav-link" data-scroll-target="#step-4-find-the-degrees-of-freedom">Step 4: Find the degrees of freedom</a></li>
  <li><a href="#step-5-find-the-p-value-and-make-a-decision" id="toc-step-5-find-the-p-value-and-make-a-decision" class="nav-link" data-scroll-target="#step-5-find-the-p-value-and-make-a-decision">Step 5: Find the p-value and make a decision</a>
  <ul class="collapse">
  <li><a href="#what-a-p-value-tells-you" id="toc-what-a-p-value-tells-you" class="nav-link" data-scroll-target="#what-a-p-value-tells-you">What a p-value tells you</a></li>
  <li><a href="#using-the-table" id="toc-using-the-table" class="nav-link" data-scroll-target="#using-the-table">Using the table</a></li>
  <li><a href="#the-result" id="toc-the-result" class="nav-link" data-scroll-target="#the-result">The result</a></li>
  </ul></li>
  <li><a href="#your-turn-combining-the-native-groups" id="toc-your-turn-combining-the-native-groups" class="nav-link" data-scroll-target="#your-turn-combining-the-native-groups">Your turn: Combining the native groups</a></li>
  <li><a href="#interpreting-the-two-analyses-together" id="toc-interpreting-the-two-analyses-together" class="nav-link" data-scroll-target="#interpreting-the-two-analyses-together">Interpreting the two analyses together</a></li>
  <li><a href="#other-ways-to-get-the-p-value" id="toc-other-ways-to-get-the-p-value" class="nav-link" data-scroll-target="#other-ways-to-get-the-p-value">Other ways to get the p-value</a></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary">Summary</a></li>
  <li><a href="#sec-chi2-table" id="toc-sec-chi2-table" class="nav-link" data-scroll-target="#sec-chi2-table">Reference A: Chi-square critical values</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Chi-Square Test of Independence: A Worked Example (Airport Routes)</h1>
<p class="subtitle lead">A self-paced lesson on testing whether two categorical variables are related</p>
  <div class="quarto-categories">
    <div class="quarto-category">chi-square</div>
    <div class="quarto-category">statistics</div>
    <div class="quarto-category">hypothesis testing</div>
  </div>
  </div>

<div>
  <div class="description">
    <p>A step-by-step, self-paced walkthrough of the chi-square test of independence, using a fictional survey of Southwestern Madison travelers and their routes to the airport. Includes a reference table of chi-square critical values.</p>
  </div>
</div>


<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Adam Ross Nelson </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">September 29, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="what-you-will-learn" class="level2">
<h2 class="anchored" data-anchor-id="what-you-will-learn">What you will learn</h2>
<p>By the end of this lesson you will be able to:</p>
<ul>
<li>Explain what a chi-square test of independence is used for.</li>
<li>State a null hypothesis and an alternative hypothesis for a chi-square test.</li>
<li>Calculate expected values from a table of counts.</li>
<li>Calculate the chi-square statistic, one cell at a time, pencil and paper-style.</li>
<li>Find the degrees of freedom and use a table to estimate a p-value.</li>
<li>Decide whether to reject or fail to reject the null hypothesis.</li>
</ul>
<p>If you are new to statistics or programming, you’re in a good place. You do not need any background in statistics or programming. Everything in this lesson is arithmetic: adding, subtracting, multiplying, dividing, and squaring. A calculator or a spreadsheet is helpful but not required.</p>
<p>This example will also be helpful for those looking for a refresher in chi-square analysis.</p>
</section>
<section id="the-big-idea" class="level2">
<h2 class="anchored" data-anchor-id="the-big-idea">The big idea</h2>
<p>Sometimes we want to know whether two categorical variables are related. A categorical variable is one whose values are categories rather than numbers, like a favorite color, a type of program, or a choice of route.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Refresher: what is a categorical variable?
</div>
</div>
<div class="callout-body-container callout-body">
<p>A categorical variable records which group an observation belongs to. You will also see these called nominal variables. The two terms are effectively interchangeable in scientific use. When the categories have a natural order (small, medium, large) some texts split them off as ordinal.</p>
<p>Examples of categorical / nominal variables:</p>
<ul>
<li>Favorite color: red, blue, green</li>
<li>Route to the airport: North, Isthmus, South</li>
<li>Where a person is from: Madison native, Greater Madison native, Transplant</li>
<li>Post-high-school outcome: work, tech school, college, military</li>
</ul>
<p>The chi-square test of independence expects two categorical variables. If one of your variables is a count or a continuous measurement, you would usually reach for a different tool (a t-test, ANOVA, correlation, or regression, depending on the question).</p>
</div>
</div>
<p>The chi-square test of independence (chi rhymes with <em>sky</em>) helps us decide between two possibilities:</p>
<ul>
<li>The two variables are independent: Knowing one cannot help you predict the other.</li>
<li>The two variables are dependent: Knowing one can help you predict the other.</li>
</ul>
</section>
<section id="the-scenario" class="level2">
<h2 class="anchored" data-anchor-id="the-scenario">The scenario</h2>
<p>Imagine the airport commissioned a survey of travelers who live in the Southwestern part of the Madison, Wisconsin metropolitan area. (The data are fictional. They were created on the <a href="./data-maker.html">Data Maker</a> page and can be previewed on the <a href="./data-preview.html">Data Preview</a> page.) The survey asked each respondent two questions.</p>
<p>Which route do you usually take to the airport?</p>
<ul>
<li>North: around the top of Lake Mendota</li>
<li>Isthmus: straight through downtown on the isthmus</li>
<li>South: east on the Beltline, then north to the airport</li>
</ul>
<p>Where are you from?</p>
<ul>
<li>Madison native</li>
<li>Greater Madison native</li>
<li>Transplant: raised somewhere else, moved to Madison for work or other reasons</li>
</ul>
<p>Every respondent gave exactly one answer to each question. There were 300 respondents in total.</p>
<p><strong>Research question:</strong> Does the route people take to the airport relate to where they are from?</p>
</section>
<section id="the-hypotheses" class="level2">
<h2 class="anchored" data-anchor-id="the-hypotheses">The hypotheses</h2>
<p>Every statistical test begins with two competing statements called hypotheses.</p>
<ul>
<li><strong>Null hypothesis:</strong> There is no relationship. The route a traveler takes to the airport is independent of where the traveler is from.</li>
<li><strong>Alternative hypothesis:</strong> There is a relationship. The route a traveler takes to the airport depends on where the traveler is from.</li>
</ul>
<p>The test works by assuming the null hypothesis is true, and then asking how surprising our data would be if that were so. If the data would be very surprising, we reject the null hypothesis.</p>
</section>
<section id="the-data" class="level2">
<h2 class="anchored" data-anchor-id="the-data">The data</h2>
<p>The data is summarized in a <strong>cross tabulation</strong>, which is a table of counts. Each row is an origin and each column is a route. Each box in the table is called a <strong>cell</strong>, and each cell counts the respondents who share that row <em>and</em> that column.</p>
<p>For example, 18 respondents were Madison natives who usually take the North route.</p>
<div id="tbl-observed" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-observed-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Observed counts, airport route survey.
</figcaption>
<div aria-describedby="tbl-observed-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th>Origin</th>
<th style="text-align: right;">North</th>
<th style="text-align: right;">Isthmus</th>
<th style="text-align: right;">South</th>
<th style="text-align: right;"><strong>TOTAL</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Madison native</strong></td>
<td style="text-align: right;">18</td>
<td style="text-align: right;">62</td>
<td style="text-align: right;">31</td>
<td style="text-align: right;">111</td>
</tr>
<tr class="even">
<td><strong>Greater Madison native</strong></td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">12</td>
<td style="text-align: right;">51</td>
<td style="text-align: right;">72</td>
</tr>
<tr class="odd">
<td><strong>Transplant</strong></td>
<td style="text-align: right;">13</td>
<td style="text-align: right;">33</td>
<td style="text-align: right;">71</td>
<td style="text-align: right;">117</td>
</tr>
<tr class="even">
<td><strong>TOTAL</strong></td>
<td style="text-align: right;">40</td>
<td style="text-align: right;">107</td>
<td style="text-align: right;">153</td>
<td style="text-align: right;">300</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>The table has three kinds of totals, which you will use again and again:</p>
<ul>
<li><strong>Row total:</strong> (right-hand column) is the number of respondents from one origin.</li>
<li><strong>Column total:</strong> (bottom row) is the number of respondents who take one route.</li>
<li><strong>Grand total:</strong> (bottom-right corner) is the number of respondents overall.</li>
</ul>
<p>The counts in the table, the numbers we actually saw, are called the observed values.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
A word about matrices
</div>
</div>
<div class="callout-body-container callout-body">
<p>A grid of numbers arranged in rows and columns is called a matrix (sounds fancier than it is). The core of the table above, without the totals, is a matrix with 3 rows and 3 columns. In this lesson you will build two more matrices of the same size. Doing the same calculation “for every cell in the matrix” is a pattern you will see often, especially once we move to Python.</p>
</div>
</div>
</section>
<section id="the-formula" class="level2">
<h2 class="anchored" data-anchor-id="the-formula">The formula</h2>
<p>Here is the formula for the chi-square statistic, which is often written as χ² or X²:</p>
<p><span id="eq-chi2"><span class="math display">\[
\chi^2 = \sum_{i=1}^{n} \frac{(Observed_i - Expected_i)^2}{Expected_i}
\tag{1}\]</span></span></p>
<p>In plain words, for each cell:</p>
<ol type="1">
<li>Subtract the expected values (the values you will calculate from the observed data) from the observed value (the actual values in the observed table).</li>
<li>Square that difference (the differences between observed and expected are known as the errors).</li>
<li>Divide by the expected value for that cell.</li>
</ol>
<p>Then add up the results from every cell. The symbol Σ (sigma) means “add up,” and the little <em>i</em> simply means “for each cell, one at a time.”</p>
<p>You already have the observed values. The next step is to find the expected values.</p>
</section>
<section id="step-1-calculate-the-expected-values" class="level2">
<h2 class="anchored" data-anchor-id="step-1-calculate-the-expected-values">Step 1: Calculate the expected values</h2>
<section id="what-is-an-expected-value" class="level3">
<h3 class="anchored" data-anchor-id="what-is-an-expected-value">What is an expected value?</h3>
<p>An expected value answers this question: If the null hypothesis were true and there were no relationship, how many respondents would we expect to see in this cell? The expected value tells us what the counts would be if where a person is from made no difference to the route they take.</p>
<p>If origin made no difference, then each origin group would use each route in the same proportions as the group overall. The expected values capture exactly that.</p>
</section>
<section id="the-recipe" class="level3">
<h3 class="anchored" data-anchor-id="the-recipe">The recipe</h3>
<p>For each cell:</p>
<p><span id="eq-expected"><span class="math display">\[
Expected = \frac{Row\ Total \times Column\ Total}{Grand\ Total}
\tag{2}\]</span></span></p>
<p>In the examples below, the colorful rings around numbers and figures help show which numbers to use, when, and how:</p>
<ul>
<li><span class="ring-green">cell</span> the cell you are working on</li>
<li><span class="ring-red">row total</span> that cell’s row total</li>
<li><span class="ring-blue">column total</span> that cell’s column total</li>
<li><span class="ring-gold">grand total</span> the grand total</li>
</ul>
</section>
<section id="worked-example-1-madison-native-north" class="level3">
<h3 class="anchored" data-anchor-id="worked-example-1-madison-native-north">Worked example 1: Madison native, North</h3>
<div id="tbl-ex1-rings" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-ex1-rings-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: Worked example 1 with Madison native, North.
</figcaption>
<div aria-describedby="tbl-ex1-rings-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 41%">
<col style="width: 12%">
<col style="width: 15%">
<col style="width: 12%">
<col style="width: 18%">
</colgroup>
<thead>
<tr class="header">
<th>Origin</th>
<th style="text-align: right;">North</th>
<th style="text-align: right;">Isthmus</th>
<th style="text-align: right;">South</th>
<th style="text-align: right;"><strong>TOTAL</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Madison native</strong></td>
<td style="text-align: right;"><span class="ring-green" aria-label="cell value">18</span></td>
<td style="text-align: right;">62</td>
<td style="text-align: right;">31</td>
<td style="text-align: right;"><span class="ring-red" aria-label="row total">111</span></td>
</tr>
<tr class="even">
<td><strong>Greater Madison native</strong></td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">12</td>
<td style="text-align: right;">51</td>
<td style="text-align: right;">72</td>
</tr>
<tr class="odd">
<td><strong>Transplant</strong></td>
<td style="text-align: right;">13</td>
<td style="text-align: right;">33</td>
<td style="text-align: right;">71</td>
<td style="text-align: right;">117</td>
</tr>
<tr class="even">
<td><strong>TOTAL</strong></td>
<td style="text-align: right;"><span class="ring-blue" aria-label="column total">40</span></td>
<td style="text-align: right;">107</td>
<td style="text-align: right;">153</td>
<td style="text-align: right;"><span class="ring-gold" aria-label="grand total">300</span></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p><span id="eq-expected-ex1"><span class="math display">\[
Expected = \frac{111 \times 40}{300} = \frac{4{,}440}{300} = 14.8
\tag{3}\]</span></span></p>
<p>If there were no relationship, we would expect about 14.8 respondents in this cell. We actually observed 18.</p>
</section>
<section id="worked-example-2-greater-madison-native-isthmus" class="level3">
<h3 class="anchored" data-anchor-id="worked-example-2-greater-madison-native-isthmus">Worked example 2: Greater Madison native, Isthmus</h3>
<div id="tbl-ex2-rings" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-ex2-rings-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3: Worked example 2 with Greater Madison native, Isthmus.
</figcaption>
<div aria-describedby="tbl-ex2-rings-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 45%">
<col style="width: 11%">
<col style="width: 14%">
<col style="width: 11%">
<col style="width: 17%">
</colgroup>
<thead>
<tr class="header">
<th>Origin</th>
<th style="text-align: right;">North</th>
<th style="text-align: right;">Isthmus</th>
<th style="text-align: right;">South</th>
<th style="text-align: right;"><strong>TOTAL</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Madison native</strong></td>
<td style="text-align: right;">18</td>
<td style="text-align: right;">62</td>
<td style="text-align: right;">31</td>
<td style="text-align: right;">111</td>
</tr>
<tr class="even">
<td><strong>Greater Madison native</strong></td>
<td style="text-align: right;">9</td>
<td style="text-align: right;"><span class="ring-green" aria-label="cell value">12</span></td>
<td style="text-align: right;">51</td>
<td style="text-align: right;"><span class="ring-red" aria-label="row total">72</span></td>
</tr>
<tr class="odd">
<td><strong>Transplant</strong></td>
<td style="text-align: right;">13</td>
<td style="text-align: right;">33</td>
<td style="text-align: right;">71</td>
<td style="text-align: right;">117</td>
</tr>
<tr class="even">
<td><strong>TOTAL</strong></td>
<td style="text-align: right;">40</td>
<td style="text-align: right;"><span class="ring-blue" aria-label="column total">107</span></td>
<td style="text-align: right;">153</td>
<td style="text-align: right;"><span class="ring-gold" aria-label="grand total">300</span></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p><span id="eq-expected-ex2"><span class="math display">\[
Expected = \frac{72 \times 107}{300} = \frac{7{,}704}{300} = 25.68
\tag{4}\]</span></span></p>
<p>Notice that the recipe never changes. Only the row and column you look up change as you move from cell to cell through the matrix.</p>
</section>
<section id="the-full-matrix-of-expected-values" class="level3">
<h3 class="anchored" data-anchor-id="the-full-matrix-of-expected-values">The full matrix of expected values</h3>
<p>Repeat the recipe for all 9 cells to get the expected values.</p>
<div id="tbl-expected" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-expected-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;4: Expected values.
</figcaption>
<div aria-describedby="tbl-expected-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 54%">
<col style="width: 13%">
<col style="width: 17%">
<col style="width: 13%">
</colgroup>
<thead>
<tr class="header">
<th>Origin</th>
<th style="text-align: right;">North</th>
<th style="text-align: right;">Isthmus</th>
<th style="text-align: right;">South</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Madison native</strong></td>
<td style="text-align: right;"><span class="ring-green" aria-label="expected value for the highlighted cell">14.80</span></td>
<td style="text-align: right;">39.59</td>
<td style="text-align: right;">56.61</td>
</tr>
<tr class="even">
<td><strong>Greater Madison native</strong></td>
<td style="text-align: right;">9.60</td>
<td style="text-align: right;"><span class="ring-green" aria-label="expected value for the highlighted cell">25.68</span></td>
<td style="text-align: right;">36.72</td>
</tr>
<tr class="odd">
<td><strong>Transplant</strong></td>
<td style="text-align: right;">15.60</td>
<td style="text-align: right;">41.73</td>
<td style="text-align: right;">59.67</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check your work
</div>
</div>
<div class="callout-body-container callout-body">
<p>The expected values in each row should add up to that row’s total, and the expected values in each column should add up to that column’s total. For example, 14.80 + 39.59 + 56.61 = 111, which is the row total for Madison native. If your sums do not match, look for an arithmetic slip.</p>
</div>
</div>
</section>
</section>
<section id="step-2-calculate-the-normalized-errors" class="level2">
<h2 class="anchored" data-anchor-id="step-2-calculate-the-normalized-errors">Step 2: Calculate the normalized errors</h2>
<p>Next, compare each observed value with its expected value. For each cell, calculate:</p>
<p><span id="eq-normerror"><span class="math display">\[
\frac{(Observed - Expected)^2}{Expected}
\tag{5}\]</span></span></p>
<p>This quantity is sometimes called a normalized error. The difference (observed minus expected) is the error. Squaring it makes every error positive, so errors in opposite directions cannot cancel each other out. Dividing by the expected value puts each error in proportion to the size of its cell.</p>
<p>Notice that the expected matrix is used twice here: Once to find the difference, and again to divide.</p>
<section id="worked-example-madison-native-north" class="level3">
<h3 class="anchored" data-anchor-id="worked-example-madison-native-north">Worked example: Madison native, North</h3>
<ul>
<li>Observed: <span class="ring-red" aria-label="observed value">18</span> (from <a href="#tbl-observed" class="quarto-xref">Table&nbsp;1</a>)</li>
<li>Expected: <span class="ring-blue" aria-label="expected value">14.80</span> (from <a href="#tbl-expected" class="quarto-xref">Table&nbsp;4</a>)</li>
</ul>
<p><span id="eq-normerror-ex1"><span class="math display">\[
\frac{(18 - 14.8)^2}{14.8} = \frac{(3.2)^2}{14.8} = \frac{10.24}{14.8} = 0.692
\tag{6}\]</span></span></p>
</section>
<section id="a-second-example-greater-madison-native-isthmus" class="level3">
<h3 class="anchored" data-anchor-id="a-second-example-greater-madison-native-isthmus">A second example: Greater Madison native, Isthmus</h3>
<p><span id="eq-normerror-ex2"><span class="math display">\[
\frac{(12 - 25.68)^2}{25.68} = \frac{(-13.68)^2}{25.68} = \frac{187.142}{25.68} = 7.287
\tag{7}\]</span></span></p>
<p>Here the difference was negative, but squaring it made the result positive.</p>
</section>
<section id="the-full-matrix-of-normalized-errors" class="level3">
<h3 class="anchored" data-anchor-id="the-full-matrix-of-normalized-errors">The full matrix of normalized errors</h3>
<div id="tbl-errors" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-errors-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;5: Normalized errors.
</figcaption>
<div aria-describedby="tbl-errors-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th>Origin</th>
<th style="text-align: right;">North</th>
<th style="text-align: right;">Isthmus</th>
<th style="text-align: right;">South</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Madison native</strong></td>
<td style="text-align: right;">0.692</td>
<td style="text-align: right;">12.685</td>
<td style="text-align: right;">11.586</td>
</tr>
<tr class="even">
<td><strong>Greater Madison native</strong></td>
<td style="text-align: right;">0.037</td>
<td style="text-align: right;">7.287</td>
<td style="text-align: right;">5.553</td>
</tr>
<tr class="odd">
<td><strong>Transplant</strong></td>
<td style="text-align: right;">0.433</td>
<td style="text-align: right;">1.826</td>
<td style="text-align: right;">2.151</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Large numbers point to cells where the observed count is far from what we would expect under no relationship. The biggest contributors are in the Isthmus and South columns for Madison natives: Madison natives took the Isthmus route more than expected (62 versus about 40) and the South route less than expected (31 versus about 57). Greater Madison natives took the Isthmus route less than expected (12 versus about 26) and the South route more than expected (51 versus about 37).</p>
</section>
</section>
<section id="step-3-add-them-up-to-get-the-chi-square-statistic" class="level2">
<h2 class="anchored" data-anchor-id="step-3-add-them-up-to-get-the-chi-square-statistic">Step 3: Add them up to get the chi-square statistic</h2>
<p>The chi-square statistic is the sum of all the normalized errors:</p>
<p><span id="eq-chi2-sum"><span class="math display">\[
\begin{aligned}
\chi^2 &amp;= 0.692 + 12.685 + 11.586 \\
       &amp;\quad + 0.037 + 7.287 + 5.553 \\
       &amp;\quad + 0.433 + 1.826 + 2.151
\end{aligned}
\tag{8}\]</span></span></p>
<p><span id="eq-chi2-result"><span class="math display">\[
\chi^2 = 42.2522
\tag{9}\]</span></span></p>
<p>That’s it. A few simple operations, repeated across the matrix, give us our chi-square statistic. This chi-square statistic is the statistic you will want to report in your manuscript, report, or results. You’ll also want to report the degrees of freedom (discussed below). Ultimately you’ll need this chi-square statistic in addition to the degrees of freedom to find the p-value, which is what will inform your decision on whether to reject (or fail to reject) the null hypothesis. Typically, you will also report the p-value when reporting your results.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Rounding
</div>
</div>
<div class="callout-body-container callout-body">
<p>If you add the rounded values above, you get 42.250. The value 42.2522 comes from carrying all the decimal places through each step. Small differences in the last decimal place are normal and do not change the conclusion.</p>
</div>
</div>
</section>
<section id="step-4-find-the-degrees-of-freedom" class="level2">
<h2 class="anchored" data-anchor-id="step-4-find-the-degrees-of-freedom">Step 4: Find the degrees of freedom</h2>
<p>To turn the chi-square statistic into a p-value, we need one more number, called the degrees of freedom (often written as <em>df</em>). For a chi-square test of independence:</p>
<p><span id="eq-df"><span class="math display">\[
df = (\text{number of rows} - 1) \times (\text{number of columns} - 1)
\tag{10}\]</span></span></p>
<p>Count only the rows and columns of categories, not the totals. Our table has 3 origins and 3 routes:</p>
<p><span id="eq-df-calc"><span class="math display">\[
df = (3 - 1) \times (3 - 1) = 2 \times 2 = 4
\tag{11}\]</span></span></p>
</section>
<section id="step-5-find-the-p-value-and-make-a-decision" class="level2">
<h2 class="anchored" data-anchor-id="step-5-find-the-p-value-and-make-a-decision">Step 5: Find the p-value and make a decision</h2>
<section id="what-a-p-value-tells-you" class="level3">
<h3 class="anchored" data-anchor-id="what-a-p-value-tells-you">What a p-value tells you</h3>
<p>The p-value is the probability of getting results as extreme as ours, or more extreme, if the null hypothesis were true. A small p-value means our data would be surprising in a world with no relationship.</p>
<p>We compare the p-value to a cutoff called the significance level. The conventional significance level is 0.05.</p>
<ul>
<li>If the p-value is less than 0.05, we reject the null hypothesis and conclude there is a relationship.</li>
<li>If the p-value is 0.05 or greater, we fail to reject the null hypothesis. We do not have enough evidence of a relationship.</li>
</ul>
</section>
<section id="using-the-table" class="level3">
<h3 class="anchored" data-anchor-id="using-the-table">Using the table</h3>
<p>The chi-square reference table (<a href="#tbl-chi2-critical" class="quarto-xref">Table&nbsp;10</a>) at the end of this lesson lets you estimate the p-value. It is a <strong>right-tailed</strong> table: the column headings are p-values, and the numbers inside the table are chi-square statistics. Bigger chi-square statistics sit farther to the right, where the p-values are smaller.</p>
<p>To use it:</p>
<ol type="1">
<li>Find the row that matches your degrees of freedom.</li>
<li>Move across that row until you find where your chi-square statistic fits between two numbers.</li>
<li>Read the p-values at the top of those two columns. Your p-value lies between them.</li>
</ol>
</section>
<section id="the-result" class="level3">
<h3 class="anchored" data-anchor-id="the-result">The result</h3>
<p>Here is an excerpt of the reference table, showing degrees of freedom 3 through 5 so you can see how the critical values change from row to row. The row we actually need (4 degrees of freedom) and the column we land beyond are both circled:</p>
<div id="tbl-df4-row" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-df4-row-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;6: Critical values for degrees of freedom 3 through 5, with the row for 4 degrees of freedom highlighted.
</figcaption>
<div aria-describedby="tbl-df4-row-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">df</th>
<th style="text-align: right;">0.995</th>
<th style="text-align: right;">0.99</th>
<th style="text-align: right;">0.975</th>
<th style="text-align: right;">0.95</th>
<th style="text-align: right;">0.90</th>
<th style="text-align: right;">0.10</th>
<th style="text-align: right;">0.05</th>
<th style="text-align: right;">0.025</th>
<th style="text-align: right;">0.01</th>
<th style="text-align: right;"><span class="ring-blue" aria-label="0.005 significance level column">0.005</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;"><strong>3</strong></td>
<td style="text-align: right;">0.072</td>
<td style="text-align: right;">0.115</td>
<td style="text-align: right;">0.216</td>
<td style="text-align: right;">0.352</td>
<td style="text-align: right;">0.584</td>
<td style="text-align: right;">6.251</td>
<td style="text-align: right;">7.815</td>
<td style="text-align: right;">9.348</td>
<td style="text-align: right;">11.345</td>
<td style="text-align: right;">12.838</td>
</tr>
<tr class="even">
<td style="text-align: right;"><span class="ring-green" aria-label="row for 4 degrees of freedom"><strong>4</strong></span></td>
<td style="text-align: right;">0.207</td>
<td style="text-align: right;">0.297</td>
<td style="text-align: right;">0.484</td>
<td style="text-align: right;">0.711</td>
<td style="text-align: right;">1.064</td>
<td style="text-align: right;">7.779</td>
<td style="text-align: right;">9.488</td>
<td style="text-align: right;">11.143</td>
<td style="text-align: right;">13.277</td>
<td style="text-align: right;"><span class="ring-blue" aria-label="critical value at the 0.005 significance level">14.860</span></td>
</tr>
<tr class="odd">
<td style="text-align: right;"><strong>5</strong></td>
<td style="text-align: right;">0.412</td>
<td style="text-align: right;">0.554</td>
<td style="text-align: right;">0.831</td>
<td style="text-align: right;">1.145</td>
<td style="text-align: right;">1.610</td>
<td style="text-align: right;">9.236</td>
<td style="text-align: right;">11.070</td>
<td style="text-align: right;">12.833</td>
<td style="text-align: right;">15.086</td>
<td style="text-align: right;">16.750</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Now walk through how to read this, one step at a time:</p>
<ol type="1">
<li><strong>Find the right row.</strong> Our test has 4 degrees of freedom, so every comparison happens along the circled row (ignore the rows for 3 and 5). We show these additional rows here only so you can see the pattern of critical values rising with df.</li>
<li><strong>Scan left to right along that row.</strong> The numbers in the row are the chi-square statistic you would need to reach to hit each p-value at the top of the table. As you move right, the p-values shrink (0.995 down to 0.005), and the critical values grow.</li>
<li><strong>Place your own chi-square statistic among them.</strong> Our statistic is <span class="ring-green" aria-label="calculated chi-square statistic">42.2522</span>. Compare this value to each critical value in the row. It’s bigger than 13.277 (the value under the 0.01 column), and it’s also bigger than 14.860 (the value under the circled 0.005 column).</li>
<li><strong>Notice it’s bigger than every value in the row.</strong> Because 42.2522 exceeds even the critical value in the smallest p-value column the table shows (0.005), our result is more extreme than anything this row directly reports.</li>
<li><strong>Translate that into a p-value.</strong> A chi-square statistic that clears the 0.005 column’s critical value means the true p-value is smaller than 0.005. This is as precise as the printed table alone can get you. It tells you a ceiling (p &lt; 0.005), not an exact number.</li>
<li><strong>Confirm with the exact value.</strong> Software can compute the precise p-value instead of just bounding it. Here, the exact p-value is about 0.000000015 (1.5 × 10⁻⁸), which is indeed smaller than 0.005 (consistent with what the table told us).</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Finding exact p-values before software
</div>
</div>
<div class="callout-body-container callout-body">
<p>Today, getting an exact p-value is one function call away. That convenience is fairly new. For most of the history of this test, researchers had no computer to ask, so they relied on printed tables like the one above.</p>
<p>Someone, working by hand or with an early mechanical calculator, had to work out the chi-square distribution’s shape for every degree of freedom and figure out exactly which value cut off the top 0.005 (or 0.05, or 0.10) of that distribution’s area. That’s a calculus problem, not an arithmetic problem, and it isn’t something you can do quickly with pencil and paper for even one value, let alone hundreds. So statisticians did that hard work once, wrote the answers down in reference tables like this one, and everyone else just looked up their result the same way you might look up a word in a dictionary rather than working out its definition from scratch every time.</p>
<p>That’s also why these tables only show a handful of columns like 0.10, 0.05, 0.025, and 0.005, instead of every possible p-value. If your chi-square statistic landed between two columns, or beyond the last one like ours did, the most honest answer available to a researcher in, say, 1950 was a range: “somewhere less than 0.005,” not an exact figure.</p>
<p>This is part of why the reject/fail-to-reject language exists at all. Historically, decisions were built around comparing a calculated statistic to a small handful of tabulated thresholds, not around reading off one precise, always-available number. Today, software has just replaced the physical page and closed the gap between columns.</p>
</div>
</div>
<p><strong>Decision:</strong> The p-value is less than 0.05, so we reject the null hypothesis. There is evidence in favor of believing that there is a relationship between where travelers are from and the route they take to the airport. We have not proven that there is a relationship. We have not proven that being from a certain place causes a traveler to choose a certain route. Merely we have rejected the null hypothesis that there is no relationship, which then means we would tend to believe the alternative hypothesis.</p>
<p>Reminder on the null and alternative hypotheses:</p>
<ul>
<li><strong>Null hypothesis (<span class="math inline">\(H_0\)</span>):</strong> There is no relationship between where travelers are from and the route they take to the airport.</li>
<li><strong>Alternative hypothesis (<span class="math inline">\(H_1\)</span>):</strong> There is a relationship between where travelers are from and the route they take to the airport.</li>
</ul>
</section>
</section>
<section id="your-turn-combining-the-native-groups" class="level2">
<h2 class="anchored" data-anchor-id="your-turn-combining-the-native-groups">Your turn: Combining the native groups</h2>
<p>Now try the full process yourself with a slightly different question. Suppose the airport does not care about the difference between Madison natives and Greater Madison natives. Combine those two rows into a single “Native” row and ask: <strong>Does the route travelers take relate to whether they are a native or a transplant?</strong></p>
<p>Here are the observed values for the combined table. (Add the Madison native and Greater Madison native rows from <a href="#tbl-observed" class="quarto-xref">Table&nbsp;1</a> to check the first row.)</p>
<div id="tbl-combined-observed" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-combined-observed-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;7: Observed counts, natives combined.
</figcaption>
<div aria-describedby="tbl-combined-observed-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th>Origin</th>
<th style="text-align: right;">North</th>
<th style="text-align: right;">Isthmus</th>
<th style="text-align: right;">South</th>
<th style="text-align: right;"><strong>TOTAL</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Native</strong></td>
<td style="text-align: right;">27</td>
<td style="text-align: right;">74</td>
<td style="text-align: right;">82</td>
<td style="text-align: right;">183</td>
</tr>
<tr class="even">
<td><strong>Transplant</strong></td>
<td style="text-align: right;">13</td>
<td style="text-align: right;">33</td>
<td style="text-align: right;">71</td>
<td style="text-align: right;">117</td>
</tr>
<tr class="odd">
<td><strong>TOTAL</strong></td>
<td style="text-align: right;">40</td>
<td style="text-align: right;">107</td>
<td style="text-align: right;">153</td>
<td style="text-align: right;">300</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Work through each step:</p>
<ol type="1">
<li>Calculate the 6 expected values (row total × column total ÷ grand total).</li>
<li>Calculate the 6 normalized errors ((observed − expected)² ÷ expected).</li>
<li>Add up the normalized errors to get the chi-square statistic.</li>
<li>Find the degrees of freedom. (Careful: the table now has only 2 rows.)</li>
<li>Use the table to estimate the p-value and make a decision.</li>
</ol>
<p>When you have finished, expand the answers below to check your work.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Answers: expected values
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div id="tbl-combined-expected" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-combined-expected-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;8: Expected values, natives combined.
</figcaption>
<div aria-describedby="tbl-combined-expected-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th>Origin</th>
<th style="text-align: right;">North</th>
<th style="text-align: right;">Isthmus</th>
<th style="text-align: right;">South</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Native</strong></td>
<td style="text-align: right;">24.40</td>
<td style="text-align: right;">65.27</td>
<td style="text-align: right;">93.33</td>
</tr>
<tr class="even">
<td><strong>Transplant</strong></td>
<td style="text-align: right;">15.60</td>
<td style="text-align: right;">41.73</td>
<td style="text-align: right;">59.67</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Answers: normalized errors
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div id="tbl-combined-errors" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-combined-errors-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;9: Normalized errors, natives combined.
</figcaption>
<div aria-describedby="tbl-combined-errors-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th>Origin</th>
<th style="text-align: right;">North</th>
<th style="text-align: right;">Isthmus</th>
<th style="text-align: right;">South</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Native</strong></td>
<td style="text-align: right;">0.277</td>
<td style="text-align: right;">1.168</td>
<td style="text-align: right;">1.375</td>
</tr>
<tr class="even">
<td><strong>Transplant</strong></td>
<td style="text-align: right;">0.433</td>
<td style="text-align: right;">1.826</td>
<td style="text-align: right;">2.151</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-8-contents" aria-controls="callout-8" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Answers: chi-square, p-value, and decision
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-8" class="callout-8-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ul>
<li>Chi-square statistic: 7.2311</li>
<li>Degrees of freedom: (2 − 1) × (3 − 1) = 2</li>
<li>In the row for 2 degrees of freedom, 7.2311 falls between 5.991 (the 0.05 column) and 7.378 (the 0.025 column). So the p-value is between 0.025 and 0.05. (The exact p-value is 0.027.)</li>
</ul>
<p><strong>Decision:</strong> The p-value is less than 0.05, so we reject the null hypothesis. There is evidence of a relationship between being a native or a transplant and the route travelers take to the airport.</p>
</div>
</div>
</div>
</section>
<section id="interpreting-the-two-analyses-together" class="level2">
<h2 class="anchored" data-anchor-id="interpreting-the-two-analyses-together">Interpreting the two analyses together</h2>
<p>Both analyses led to the same decision, but the evidence was much stronger when we kept the three origin groups separate (p about 0.000000015) than when we combined the two native groups (p about 0.027). Combining categories threw away information: Madison natives and Greater Madison natives behave differently from each other, and lumping them together blurred that difference.</p>
<p>Keep in mind, too, that a chi-square test tells you whether two variables are related. It does not, on its own, tell you that one variable caused the other. It also does not tell you which cells drive the result. The normalized errors help with that, because they point to the cells that contribute the most.</p>
<p>Remember also that the data here are fictional, and that we built the relationship into the data ourselves on the Data Maker page. In real survey work you would also want to think about how respondents were selected, since a sample that is not representative of travelers can distort the results.</p>
</section>
<section id="other-ways-to-get-the-p-value" class="level2">
<h2 class="anchored" data-anchor-id="other-ways-to-get-the-p-value">Other ways to get the p-value</h2>
<p>The table gives you a range. Software can give you the exact p-value. In Excel, there are two functions for this.</p>
<p>Excel’s function <code>CHISQ.TEST()</code> compares the observed values with the expected values and returns the p-value directly. You give it the observed range first and the expected range second:</p>
<pre><code>=CHISQ.TEST(observed range, expected range)</code></pre>
<p>Excel’s function <code>CHISQ.DIST.RT()</code> converts a chi-square statistic into a p-value. You give it the chi-square statistic and the degrees of freedom:</p>
<pre><code>=CHISQ.DIST.RT(chi-square statistic, degrees of freedom)</code></pre>
<p>For the combined-natives table, <code>=CHISQ.DIST.RT(7.2311, 2)</code> returns 0.027.</p>
<p>In upcoming tutorials, you will learn to carry out this same analysis in Python. Every step you did by hand here, from the expected values to the final p-value, has a direct counterpart in code.</p>
<p>There are also websites that will find the p-value for free if you know the chi2 and df statistics.</p>
<ul>
<li><a href="https://es.wolframalpha.com/calculators/mathematics-statistics-probability-distributions-probabilities-for-the-chi-squared-distribution-calculator">Probabilities for the Chi‐Squared Distribution Calculator - WolframAplha.com</a></li>
<li><a href="https://www.socscistatistics.com/pvalues/chidistribution/calculator/">Chi-Square to P-Value Calculator - SocialStatistics.com</a></li>
<li><a href="https://www.graphpad.com/quickcalcs/pvalue1/">P Value Calculator - GraphPad.com</a></li>
<li><a href="https://statcalc.net/p-value-from-chi-square-calculator/">P-Value From Chi-Square Calculator - StatCalc.net</a></li>
</ul>
</section>
<section id="summary" class="level2">
<h2 class="anchored" data-anchor-id="summary">Summary</h2>
<ol type="1">
<li>State the null hypothesis (no relationship) and the alternative hypothesis (a relationship).</li>
<li>Organize the observed counts in a cross tabulation with row, column, and grand totals.</li>
<li>For each cell, calculate the expected value: row total × column total ÷ grand total.</li>
<li>For each cell, calculate the normalized error: (observed − expected)² ÷ expected.</li>
<li>Add up the normalized errors to get the chi-square statistic.</li>
<li>Find the degrees of freedom: (rows − 1) × (columns − 1).</li>
<li>Use the table (or software) to find the p-value.</li>
<li>If the p-value is less than 0.05, reject the null hypothesis. Otherwise, fail to reject it.</li>
</ol>
</section>
<section id="sec-chi2-table" class="level2">
<h2 class="anchored" data-anchor-id="sec-chi2-table">Reference A: Chi-square critical values</h2>
<p>Find the row for your degrees of freedom. The column headings are right-tail p-values. If your chi-square statistic falls between two numbers in the row, your p-value falls between the two column headings.</p>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Use scipy to create a table of p-values based on critical values and df</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy <span class="im">import</span> stats</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>p_values <span class="op">=</span> [<span class="fl">0.995</span>, <span class="fl">0.99</span>, <span class="fl">0.975</span>, <span class="fl">0.95</span>, <span class="fl">0.90</span>, <span class="fl">0.10</span>, <span class="fl">0.05</span>, <span class="fl">0.025</span>, <span class="fl">0.01</span>, <span class="fl">0.005</span>]</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"| df | "</span> <span class="op">+</span> <span class="st">" | "</span>.join(<span class="bu">str</span>(p) <span class="cf">for</span> p <span class="kw">in</span> p_values) <span class="op">+</span> <span class="st">" |"</span>)</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"|---:|"</span> <span class="op">+</span> <span class="st">"---:|"</span> <span class="op">*</span> <span class="bu">len</span>(p_values))</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> df <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">1</span>, <span class="dv">21</span>):</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>    row <span class="op">=</span> [<span class="ss">f"</span><span class="sc">{</span>stats<span class="sc">.</span>chi2<span class="sc">.</span>isf(p, df)<span class="sc">:.3f}</span><span class="ss">"</span> <span class="cf">for</span> p <span class="kw">in</span> p_values]</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"| **</span><span class="sc">{</span>df<span class="sc">}</span><span class="ss">** | "</span> <span class="op">+</span> <span class="st">" | "</span>.join(row) <span class="op">+</span> <span class="st">" |"</span>)</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>()</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">": Chi-square critical values by degrees of freedom. {#tbl-chi2-critical}"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div id="tbl-chi2-critical" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-chi2-critical-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;10: Chi-square critical values by degrees of freedom.
</figcaption>
<div aria-describedby="tbl-chi2-critical-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">df</th>
<th style="text-align: right;">0.995</th>
<th style="text-align: right;">0.99</th>
<th style="text-align: right;">0.975</th>
<th style="text-align: right;">0.95</th>
<th style="text-align: right;">0.9</th>
<th style="text-align: right;">0.1</th>
<th style="text-align: right;">0.05</th>
<th style="text-align: right;">0.025</th>
<th style="text-align: right;">0.01</th>
<th style="text-align: right;">0.005</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;"><strong>1</strong></td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.001</td>
<td style="text-align: right;">0.004</td>
<td style="text-align: right;">0.016</td>
<td style="text-align: right;">2.706</td>
<td style="text-align: right;">3.841</td>
<td style="text-align: right;">5.024</td>
<td style="text-align: right;">6.635</td>
<td style="text-align: right;">7.879</td>
</tr>
<tr class="even">
<td style="text-align: right;"><strong>2</strong></td>
<td style="text-align: right;">0.010</td>
<td style="text-align: right;">0.020</td>
<td style="text-align: right;">0.051</td>
<td style="text-align: right;">0.103</td>
<td style="text-align: right;">0.211</td>
<td style="text-align: right;">4.605</td>
<td style="text-align: right;">5.991</td>
<td style="text-align: right;">7.378</td>
<td style="text-align: right;">9.210</td>
<td style="text-align: right;">10.597</td>
</tr>
<tr class="odd">
<td style="text-align: right;"><strong>3</strong></td>
<td style="text-align: right;">0.072</td>
<td style="text-align: right;">0.115</td>
<td style="text-align: right;">0.216</td>
<td style="text-align: right;">0.352</td>
<td style="text-align: right;">0.584</td>
<td style="text-align: right;">6.251</td>
<td style="text-align: right;">7.815</td>
<td style="text-align: right;">9.348</td>
<td style="text-align: right;">11.345</td>
<td style="text-align: right;">12.838</td>
</tr>
<tr class="even">
<td style="text-align: right;"><strong>4</strong></td>
<td style="text-align: right;">0.207</td>
<td style="text-align: right;">0.297</td>
<td style="text-align: right;">0.484</td>
<td style="text-align: right;">0.711</td>
<td style="text-align: right;">1.064</td>
<td style="text-align: right;">7.779</td>
<td style="text-align: right;">9.488</td>
<td style="text-align: right;">11.143</td>
<td style="text-align: right;">13.277</td>
<td style="text-align: right;">14.860</td>
</tr>
<tr class="odd">
<td style="text-align: right;"><strong>5</strong></td>
<td style="text-align: right;">0.412</td>
<td style="text-align: right;">0.554</td>
<td style="text-align: right;">0.831</td>
<td style="text-align: right;">1.145</td>
<td style="text-align: right;">1.610</td>
<td style="text-align: right;">9.236</td>
<td style="text-align: right;">11.070</td>
<td style="text-align: right;">12.833</td>
<td style="text-align: right;">15.086</td>
<td style="text-align: right;">16.750</td>
</tr>
<tr class="even">
<td style="text-align: right;"><strong>6</strong></td>
<td style="text-align: right;">0.676</td>
<td style="text-align: right;">0.872</td>
<td style="text-align: right;">1.237</td>
<td style="text-align: right;">1.635</td>
<td style="text-align: right;">2.204</td>
<td style="text-align: right;">10.645</td>
<td style="text-align: right;">12.592</td>
<td style="text-align: right;">14.449</td>
<td style="text-align: right;">16.812</td>
<td style="text-align: right;">18.548</td>
</tr>
<tr class="odd">
<td style="text-align: right;"><strong>7</strong></td>
<td style="text-align: right;">0.989</td>
<td style="text-align: right;">1.239</td>
<td style="text-align: right;">1.690</td>
<td style="text-align: right;">2.167</td>
<td style="text-align: right;">2.833</td>
<td style="text-align: right;">12.017</td>
<td style="text-align: right;">14.067</td>
<td style="text-align: right;">16.013</td>
<td style="text-align: right;">18.475</td>
<td style="text-align: right;">20.278</td>
</tr>
<tr class="even">
<td style="text-align: right;"><strong>8</strong></td>
<td style="text-align: right;">1.344</td>
<td style="text-align: right;">1.646</td>
<td style="text-align: right;">2.180</td>
<td style="text-align: right;">2.733</td>
<td style="text-align: right;">3.490</td>
<td style="text-align: right;">13.362</td>
<td style="text-align: right;">15.507</td>
<td style="text-align: right;">17.535</td>
<td style="text-align: right;">20.090</td>
<td style="text-align: right;">21.955</td>
</tr>
<tr class="odd">
<td style="text-align: right;"><strong>9</strong></td>
<td style="text-align: right;">1.735</td>
<td style="text-align: right;">2.088</td>
<td style="text-align: right;">2.700</td>
<td style="text-align: right;">3.325</td>
<td style="text-align: right;">4.168</td>
<td style="text-align: right;">14.684</td>
<td style="text-align: right;">16.919</td>
<td style="text-align: right;">19.023</td>
<td style="text-align: right;">21.666</td>
<td style="text-align: right;">23.589</td>
</tr>
<tr class="even">
<td style="text-align: right;"><strong>10</strong></td>
<td style="text-align: right;">2.156</td>
<td style="text-align: right;">2.558</td>
<td style="text-align: right;">3.247</td>
<td style="text-align: right;">3.940</td>
<td style="text-align: right;">4.865</td>
<td style="text-align: right;">15.987</td>
<td style="text-align: right;">18.307</td>
<td style="text-align: right;">20.483</td>
<td style="text-align: right;">23.209</td>
<td style="text-align: right;">25.188</td>
</tr>
<tr class="odd">
<td style="text-align: right;"><strong>11</strong></td>
<td style="text-align: right;">2.603</td>
<td style="text-align: right;">3.053</td>
<td style="text-align: right;">3.816</td>
<td style="text-align: right;">4.575</td>
<td style="text-align: right;">5.578</td>
<td style="text-align: right;">17.275</td>
<td style="text-align: right;">19.675</td>
<td style="text-align: right;">21.920</td>
<td style="text-align: right;">24.725</td>
<td style="text-align: right;">26.757</td>
</tr>
<tr class="even">
<td style="text-align: right;"><strong>12</strong></td>
<td style="text-align: right;">3.074</td>
<td style="text-align: right;">3.571</td>
<td style="text-align: right;">4.404</td>
<td style="text-align: right;">5.226</td>
<td style="text-align: right;">6.304</td>
<td style="text-align: right;">18.549</td>
<td style="text-align: right;">21.026</td>
<td style="text-align: right;">23.337</td>
<td style="text-align: right;">26.217</td>
<td style="text-align: right;">28.300</td>
</tr>
<tr class="odd">
<td style="text-align: right;"><strong>13</strong></td>
<td style="text-align: right;">3.565</td>
<td style="text-align: right;">4.107</td>
<td style="text-align: right;">5.009</td>
<td style="text-align: right;">5.892</td>
<td style="text-align: right;">7.042</td>
<td style="text-align: right;">19.812</td>
<td style="text-align: right;">22.362</td>
<td style="text-align: right;">24.736</td>
<td style="text-align: right;">27.688</td>
<td style="text-align: right;">29.819</td>
</tr>
<tr class="even">
<td style="text-align: right;"><strong>14</strong></td>
<td style="text-align: right;">4.075</td>
<td style="text-align: right;">4.660</td>
<td style="text-align: right;">5.629</td>
<td style="text-align: right;">6.571</td>
<td style="text-align: right;">7.790</td>
<td style="text-align: right;">21.064</td>
<td style="text-align: right;">23.685</td>
<td style="text-align: right;">26.119</td>
<td style="text-align: right;">29.141</td>
<td style="text-align: right;">31.319</td>
</tr>
<tr class="odd">
<td style="text-align: right;"><strong>15</strong></td>
<td style="text-align: right;">4.601</td>
<td style="text-align: right;">5.229</td>
<td style="text-align: right;">6.262</td>
<td style="text-align: right;">7.261</td>
<td style="text-align: right;">8.547</td>
<td style="text-align: right;">22.307</td>
<td style="text-align: right;">24.996</td>
<td style="text-align: right;">27.488</td>
<td style="text-align: right;">30.578</td>
<td style="text-align: right;">32.801</td>
</tr>
<tr class="even">
<td style="text-align: right;"><strong>16</strong></td>
<td style="text-align: right;">5.142</td>
<td style="text-align: right;">5.812</td>
<td style="text-align: right;">6.908</td>
<td style="text-align: right;">7.962</td>
<td style="text-align: right;">9.312</td>
<td style="text-align: right;">23.542</td>
<td style="text-align: right;">26.296</td>
<td style="text-align: right;">28.845</td>
<td style="text-align: right;">32.000</td>
<td style="text-align: right;">34.267</td>
</tr>
<tr class="odd">
<td style="text-align: right;"><strong>17</strong></td>
<td style="text-align: right;">5.697</td>
<td style="text-align: right;">6.408</td>
<td style="text-align: right;">7.564</td>
<td style="text-align: right;">8.672</td>
<td style="text-align: right;">10.085</td>
<td style="text-align: right;">24.769</td>
<td style="text-align: right;">27.587</td>
<td style="text-align: right;">30.191</td>
<td style="text-align: right;">33.409</td>
<td style="text-align: right;">35.718</td>
</tr>
<tr class="even">
<td style="text-align: right;"><strong>18</strong></td>
<td style="text-align: right;">6.265</td>
<td style="text-align: right;">7.015</td>
<td style="text-align: right;">8.231</td>
<td style="text-align: right;">9.390</td>
<td style="text-align: right;">10.865</td>
<td style="text-align: right;">25.989</td>
<td style="text-align: right;">28.869</td>
<td style="text-align: right;">31.526</td>
<td style="text-align: right;">34.805</td>
<td style="text-align: right;">37.156</td>
</tr>
<tr class="odd">
<td style="text-align: right;"><strong>19</strong></td>
<td style="text-align: right;">6.844</td>
<td style="text-align: right;">7.633</td>
<td style="text-align: right;">8.907</td>
<td style="text-align: right;">10.117</td>
<td style="text-align: right;">11.651</td>
<td style="text-align: right;">27.204</td>
<td style="text-align: right;">30.144</td>
<td style="text-align: right;">32.852</td>
<td style="text-align: right;">36.191</td>
<td style="text-align: right;">38.582</td>
</tr>
<tr class="even">
<td style="text-align: right;"><strong>20</strong></td>
<td style="text-align: right;">7.434</td>
<td style="text-align: right;">8.260</td>
<td style="text-align: right;">9.591</td>
<td style="text-align: right;">10.851</td>
<td style="text-align: right;">12.443</td>
<td style="text-align: right;">28.412</td>
<td style="text-align: right;">31.410</td>
<td style="text-align: right;">34.170</td>
<td style="text-align: right;">37.566</td>
<td style="text-align: right;">39.997</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/adamrossnelson\.github\.io\/airport-chi2\/");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>